name: "GSheet to InfluxDB"
description: "This add-on read a Google Spreadsheet and loads its data to InfluxDB"
version: "1.0.0"
slug: "gsheet-to-influxdb"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services